using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Core.Localization.SourceGenerator;

[Generator]
public class LocalizationSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Watch for .json and .yaml files
        var localizationFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".json") || file.Path.EndsWith(".yaml"));

        var provider = localizationFiles.Select((text, ct) => 
        {
            var content = text.GetText(ct)?.ToString();
            var fileName = Path.GetFileNameWithoutExtension(text.Path);
            return new { FileName = fileName, Content = content };
        });

        context.RegisterSourceOutput(provider.Collect(), (spc, files) =>
        {
            if (files.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace Core.Localization;");
            sb.AppendLine();
            sb.AppendLine("public static partial class L");
            sb.AppendLine("{");

            var keys = new HashSet<string>();

            foreach (var file in files)
            {
                if (string.IsNullOrEmpty(file.Content)) continue;

                // Simple regex-based key extraction
                var matches = Regex.Matches(file.Content, @"""(?<key>[^""]+)""\s*:");
                foreach (Match match in matches)
                {
                    keys.Add(match.Groups["key"].Value);
                }
                
                var yamlMatches = Regex.Matches(file.Content, @"^(?<key>[^:\s#]+)\s*:", RegexOptions.Multiline);
                foreach (Match match in yamlMatches)
                {
                    keys.Add(match.Groups["key"].Value);
                }
            }

            foreach (var key in keys.OrderBy(k => k))
            {
                var safeName = SanitizeName(key);
                if (string.IsNullOrEmpty(safeName)) continue;

                sb.AppendLine($"    /// <summary>Returns localization key: {key}</summary>");
                sb.AppendLine($"    public const string {safeName} = \"{key}\";");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            spc.AddSource("L.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private string SanitizeName(string name)
    {
        var sanitized = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
        if (string.IsNullOrEmpty(sanitized)) return "Key";
        if (char.IsDigit(sanitized[0])) sanitized = "_" + sanitized;
        return sanitized;
    }
}
